### ISSUE TITLE
Github actions template

### ISSUE THREAD

**Issue by aminya** [idleberg/generator-atom-package-typescript#7]
It would nice to have Github actions CI in addition to CircleCI/TravisCI

**Comment by idleberg** [comment]
That's a good idea. I'm now subscribed to [this discussion](https://github.com/actions/setup-node/issues/26), since I would want my implementation to follow CircleCI/TravisCI and work with both, latest and LTS versions of Node.

There are some substantial changes coming to this packages and it might be moved to another repository before GitHub Actions have been implemented. I will try and post an update here.

**Comment by idleberg** [comment]
This package will soon be deprecated in favour of [@atxm/generator-package](https://github.com/a-t-x-m/generator-package). That package now contains support for GitHub actions!
